### ISSUE TITLE
Android crash in release mode (no using proguard)

### ISSUE THREAD

**Issue by chanphiromsok** [numandev1/react-native-keys#57] opened 2023-09-28 04:24 UTC
### Current behavior
Image below is error with expo prebuild
<img width="1620" alt="Screen Shot 2023-09-28 at 11 22 24 AM" src="https://github.com/numandev1/react-native-keys/assets/65760336/573b1c9c-46d9-4154-8b59-291ddfc12284">

### Platform

- [X] Android
- [ ] iOS

### Reproduce
- run KEYSFILE=keys.staging.json yarn android --variant=release

**Comment by efstathiosntonas** [comment] 2023-09-28 05:05
duplicate of https://github.com/numandev1/react-native-keys/issues/18

**Comment by efstathiosntonas** [comment] 2023-09-28 05:07
@chanphiromsok are you using expo-crypto?

**Comment by chanphiromsok** [comment] 2023-09-28 05:07
> @chanphiromsok are you using expo-crypto?

No I didn't installed it

**Closed** 2023-09-28 23:50 UTC

**Comment by numandev1** [comment] 2023-09-28 23:52
@chanphiromsok can you try `0.7.5` version?

**Comment by chanphiromsok** [comment] 2023-09-29 10:02
> @chanphiromsok can you try `0.7.5` version?

yep what a sweet PR hahaha

**Comment by numandev1** [comment] 2023-09-29 12:46
is it working good?

**Comment by chanphiromsok** [comment] 2023-10-05 11:35
> is it working good?

yes 💪

**Comment by numandev1** [comment] 2023-10-05 11:44
@chanphiromsok thanks a lot ❤ ❤, it was not possible without your help

**Comment by chanphiromsok** [comment] 2023-10-05 11:57
> @chanphiromsok thanks a lot ❤ ❤, it was not possible without your help

you are the good developers with high responsibility🫡
